name: markeet
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_pro: ^1.0.0

  clay_containers: ^0.2.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  progress_dialog: ^1.2.0

  data_connection_checker: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  fluttertoast: ^3.1.0
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
    - images/app_logo.png
    - images/app_logo2.png
    - images/img1.jpg
    - images/img2.jpg
    - images/img3.png
    - images/img4.png
    - images/img5.jpg
    - images/img6.jpg
    - images/ball2.jpg
    - images/discountimg.jpg
    - images/beautiimg.jpg
    - images/babiesimg.jpg
    - images/fashionimg.jpg
    - images/gadgetsimg.jpg
    - images/homeimg.jpg
    - images/sportimg.jpg
    - images/serviceimg.jpg
    - images/apple.jpg
    - images/badminton.jpg
    - images/bagmen.jpg
    - images/bagwomen.jpg
    - images/bledger.jpg
    - images/bledger2.jpg
    - images/delight.jpg
    - images/ladydress.jpg
    - images/magaschoni.jpg
    - images/magic.jpg
    - images/men2.jpg
    - images/mens.jpg
    - images/natural.jpg
    - images/packseries.jpg
    - images/plets.jpg
    - images/prostar.jpg
    - images/reachelpally.jpg
    - images/ring.jpg
    - images/room.jpg
    - images/samsong.jpg
    - images/sent.jpg
    - images/sent2.jpg
    - images/sent3.jpg
    - images/shoes.jpg
    - images/sofa.jpg
    - images/sofia.jpg
    - images/stroller.jpg
    - images/sweater.jpg
    - images/velvet.jpg
    - images/vitamin.jpg
    - images/watch.jpg
    - images/adidassent.jpg
    - images/asus1.jpg
    - images/asus2.jpg
    - images/babysoes.jpg
    - images/ball.jpg
    - images/biggoot.jpg
    - images/bike.jpg
    - images/blockcreative.jpg
    - images/body.jpg
    - images/cofee.jpg
    - images/coffetable.jpg
    - images/computertable.jpg
    - images/concern.jpg
    - images/cubedining.jpg
    - images/deeprider.jpg
    - images/floradres.jpg
    - images/intex.jpg
    - images/jasmine.jpg
    - images/jazz.jpg
    - images/kurkure.jpg
    - images/lenevolaptop.jpg
    - images/macbook.jpg
    - images/natural.jpg
    - images/oppo.jpg
    - images/oreo.jpg
    - images/oyster.jpg
    - images/packseries.jpg
    - images/riversafari.jpg
    - images/powertool.jpg
    - images/shoes.jpg
    - images/singapore.jpg
    - images/sony.jpg
    - images/unitsteel.jpg
    - images/packseries.jpg
    - images/yottaride.jpg
    - images/double.jpg
    - images/phone.png
    - images/fashion.jpeg
    - images/health.jpg
    - images/babieswithtoy.jpeg
    - images/home.png
    - images/cmp.jpeg
    


  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
